Add Interval Generator
laravel/cashier-mollie pull request #287
Opened 2021-01-11 08:28 UTC by ciungulete

- You can charge user monthly using Carbon addMonthsNoOverflow or you can use default generator.
- Can be used:
     - `interval => '1 month'` 
   - `interval' => [ 
'value' => 1,
'period' => 'month', 
'fixed' => false,
]`

2021-01-11 15:08 UTC, sandervanhooft commented
Hi @ciungulete,

Can you

a) extract the interval generation logic into a _dedicated_ class (`PlanInterval::generate($args ...);`)?
b) the config then becomes something like:

```php
// default 
'interval' => '1 month',

// override
'interval' => [
    'class' => Laravel\Cashier\Plan\SomeSpecialIntervalGenerator::class, // or LegacyIntervalGenerator, or whatever...
    'arguments' => [
        // ...
        // all arguments here get passed in as spread
    ],
],
```

This would make it the most flexible for future modifications I think

2021-02-01 17:27 UTC, sandervanhooft commented
Interesting to see what's evolving here. I think we now in fact try to support 3 use cases / generators.

1. string based, Cashier v1. This should be called the `LegacyCarbonBasedIntervalGenerator`. This means if people want to keep on using this after upgrading, they should update the config.
2. string based, Cashier v2 with fixed = true. This is going to be the new "default". It's easiest to use and most merchants want this interval calculation behaviour. Perhaps the best name is `V2StringBasedIntervalGenerator`? This also means that on upgrade to v2, without modification to the config this generator is automatically used.
3. Advanced `V2AdvancedIntervalGenerator`

```php
// use case 1: string based, Cashier v1. This should be called the LegacyCarbonBasedIntervalGenerator
'interval' => [
    'generator' => LegacyCarbonBasedIntervalGenerator::class,
    'value' => '1 month',
],

// use case 2
'interval' => '1 month', 

// use case 3
'interval' => [
     'generator' => DefaultIntervalGenerator::class,
     'value' => 1,
     'period' => 'month', /* day, month or year*/
     'fixed' => false, /*  If fixed is true the interval is Carbon Base Interval Generator use NoOverflow, */
 ],

```

Makes sense? 🤔

2021-02-01 17:33 UTC, sandervanhooft commented
I'm ok with keeping the name `DefaultIntervalGenerator`, but I think the wrong class is carrying that name right now. The `V2StringBasedIntervalGenerator` could be called `DefaultIntervalGenerator`.

2021-02-01 18:05 UTC, ciungulete commented
We have only two cases here, one with two options
```php
// 1.a (using DefaultIntervalGenerator - the old one)
'interval' => '1 month', 
//1.b (return same result like 1.a)
 'interval' => [
     'generator' => DefaultIntervalGenerator::class,
     'value' => 1,
     'period' => 'month', /* day, month or year*/
     'fixed' => false, /*  If fixed is true the interval is Carbon Base Interval Generator use NoOverflow, */
 ],

// 2.
'interval' => [
     'generator' => AdvancedIntervalGenerator::class,
     'value' => 1,
     'period' => 'month', /* day, month or year*/
     'fixed' => false, /*  If fixed is true the interval is Carbon Base Interval Generator use NoOverflow, */
 ],
```

2021-02-01 21:37 UTC, sandervanhooft commented
The problem is that if I do a new installation I want to set

```php
'interval' => '1 month', 
```

AND have `noOverflow` enabled + base the subsequent intervals on the subscription start date. This is what most merchants want so we should make it the easiest to use / the default.

2021-02-01 21:38 UTC, sandervanhooft commented
Another thing to be aware of:

> base the subsequent intervals on the subscription start date

this is not the whole story. A subscription can start with a trial. So we need to take the `trial_ends_at` into account too.

2021-02-01 21:59 UTC, ciungulete commented
> A subscription can start with a trial. So we need to take the `trial_ends_at` into account too.

Yes you are right.

2021-02-01 23:30 UTC, ciungulete commented
> The problem is that if I do a new installation I want to set
> 
> ```
> 'interval' => '1 month', 
> ```
> 
> AND have `noOverflow` enabled + base the subsequent intervals on the subscription start date. This is what most merchants want so we should make it the easiest to use / the default.

I will swap classes, but need to refactor tests... now use the old way for strings

2021-02-02 15:42 UTC, sandervanhooft requested changes
Almost there. Some little stuff

2021-02-02 15:42 UTC, sandervanhooft commented on src/Plan/BaseIntervalGenerator.php
> +        return $subscription_started_at = $subscription->created_at ?? now();
Can return directly

2021-02-02 15:42 UTC, sandervanhooft commented on src/Plan/Contracts/IntervalGeneratorContract.php
> +    public function getEndOfTheNextSubscriptionCycle(Subscription  $subscription = null);
Remove double space before `$subscription`.
Rename to `getEndOfNextSubscriptionCycle`

2021-02-02 15:42 UTC, sandervanhooft commented on src/Plan/DefaultIntervalGenerator.php
> +            return $cycle_ends_at->addMonthsNoOverflow((int) filter_var($this->interval, FILTER_SANITIZE_NUMBER_INT))
Nice

2021-02-02 15:42 UTC, sandervanhooft commented on src/Plan/Plan.php
> +     * The billing period.
The billing interval generator

2021-02-02 15:42 UTC, sandervanhooft commented on config/cashier_plans.php
> +            // 'interval' => 1 month or
Wrap `1 month` in parantheses `"`

2021-02-02 15:42 UTC, sandervanhooft commented on config/cashier_plans.php
> +                'fixed' => false, /*  If fixed is true the interval is Carbon Base Interval Generator use NoOverflow, */
Do you have a suggestion for a variable name that is more verbose, more clear about what it does?

2021-02-03 09:52 UTC, sandervanhooft commented
Stellar! Thanks @ciungulete !

2021-02-03 09:52 UTC, merged